Repository hmcts/ccd-api-gateway, pull requests merged in 2019-02, with the labels that each got.

#166 Bump extend to v3.0.2
  yarn.lock
Labels: ns:ccd-api-gateway-web-pr-166

#171 Add stale bot config
  .github/stale.yml
Labels: ns:ccd-api-gateway-web-pr-171

#174 Switch to SIDAM for testing
  infrastructure/saat.tfvars
Labels: ns:ccd-api-gateway-web-pr-174

#173 Use ACR cache optimisation in pipeline
  .dockerignore
  Dockerfile
  acb.tpl.yaml
Labels: ns:ccd-api-gateway-web-pr-173

#179 Bump just-extend from 3.0.0 to 4.0.2
  yarn.lock
Labels: dependencies, devDependencies, ns:ccd-api-gateway-web-pr-179, security

#177 Remove hmcts user as it will be the default user
  Dockerfile
Labels: docker-optimisation, ns:ccd-api-gateway-web-pr-177
