Repository hmcts/ccd-api-gateway, pull requests merged in 2019-10, with the labels that each got.

#248 Upgrade base chart for hmcts demo
  charts/ccd-api-gateway-web/Chart.yaml
  charts/ccd-api-gateway-web/requirements.yaml
  charts/ccd-api-gateway-web/values.aat.template.yaml
  charts/ccd-api-gateway-web/values.preview.template.yaml
  charts/ccd-api-gateway-web/values.yaml
Labels: ns:ccd-api-gateway-web-pr-248

#251 RDM-5963 RDM-5964 vulnerabilities fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd-api-gateway-web-pr-251

#255 Rdm 5582 upgrade mv version for annotations
  infrastructure/ithc.tfvars
Labels: ns:ccd-api-gateway-web-pr-255
