Repository hmcts/ccd-api-gateway, pull requests merged in 2019-07, with the labels that each got.

#227 CCD-gateway-REFDATA-Configuration
  app.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
Labels: ns:ccd-api-gateway-web-pr-227

#235 RDM-5330-update ccd to use new docker registry url
  Dockerfile
  acb.tpl.yaml
  docker-compose.yml
Labels: ns:ccd-api-gateway-web-pr-235

#236 RDM-5301 - yarn audit with suppression script
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd-api-gateway-web-pr-236

#237 PAY-1732 -> Telephony MVP
  app.js
Labels: ns:ccd-api-gateway-web-pr-237
