Repository hmcts/ccd-api-gateway, pull requests merged in 2020-04, with the labels that each got.

#314 RDM-8096
  charts/ccd-api-gateway-web/values.preview.template.yaml
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-314

#299 RDM-7843-Stale-PR
  .github/stale.yml
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-299

#312 Open ID Connect Changes
  app/user/auth-checker-user-only-filter.js
  app/user/user-request-authorizer.js
  app/user/user-resolver.js
  test/user/auth-checker-user-only-filter.spec.js
  test/user/user-request-authorizer.spec.js
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-312
