Repository hmcts/ccd-api-gateway, pull requests merged in 2020-03, with the labels that each got.

#298 Enable AKS on AAT
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-298

#302 Point api-gateway to go to service for print service
  charts/ccd-api-gateway-web/Chart.yaml
  charts/ccd-api-gateway-web/values.preview.template.yaml
  charts/ccd-api-gateway-web/values.yaml
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-302

#303 Rdm 7887 anno url
  charts/ccd-api-gateway-web/Chart.yaml
  charts/ccd-api-gateway-web/values.yaml
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-303

#305 RDM-7867-Update-base-chart
  charts/ccd-api-gateway-web/Chart.yaml
  charts/ccd-api-gateway-web/requirements.yaml
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-305

#306 RDM-7899-Slack
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-306

#297 RDM-7804 - CCD api gateway to OIDC
  app/user/auth-checker-user-only-filter.js
  app/user/user-request-authorizer.js
  app/user/user-resolver.js
  test/user/auth-checker-user-only-filter.spec.js
  test/user/user-request-authorizer.spec.js
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-297

#304 Release cut 17.2
  Dockerfile
  charts/ccd-api-gateway-web/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-304

#309 Update IDAM URL
  infrastructure/perftest.tfvars
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-309

#310 AKS live migration
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-310

#311 Revert "Update IDAM URL"
  infrastructure/perftest.tfvars
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-311

#313 terraform cleanup
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-313
