Repository hmcts/ccd-api-gateway, pull requests merged in 2020-02, with the labels that each got.

#285 Release cut 17.1
  web.config
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-285

#288 RDM-7554 Remove the deprecated enableDockerBuild
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-288

#272 RDM-3593 Upgrade node to 12.x
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  hub.Dockerfile
  infrastructure/main.tf
  package.json
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-272

#289 RDM-3593 Upgrade node to 12.x - MASTER
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  hub.Dockerfile
  infrastructure/main.tf
  package.json
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-289

#290 AKS migration
  Dockerfile
  Jenkinsfile_CNP
  app/app-insights/app-insights.js
  app/service/service-token-generator.js
  charts/ccd-api-gateway-web/Chart.yaml
  charts/ccd-api-gateway-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-290

#292 RDM-7695 Update-IDAM-URLs
  infrastructure/ithc.tfvars
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-292

#295 Fix NodeJS version to match AZ runtime
  package.json
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-295

#296 RDM-2508-Rm-nsp
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-api-gateway-web-pr-296
