Repository hmcts/ccd-api-gateway, pull requests merged in 2021-07, with the labels that each got.

#381 Nightly ccd 1252
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-381

#384 CVE-2021-32640
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-384

#386 fix for Fortify Issue 14718112 - Dockerfile Misconfiguration
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-386
