Repository hmcts/ccd-api-gateway, pull requests merged in 2022-01, with the labels that each got.

#400 CCD-2293: Update hmcts/properties-volume dependency version
  package.json
  yarn.lock
Labels: stale, ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-400

#407 CCD-2424: Address CVE-2022-0155
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-407

#409 CCD-2460: Remove redundant integration test and associated files
  integration_test/pom.xml
  integration_test/src/test/java/uk/gov/hmcts/ccd/api/gateway/ApiGatewayIT.java
  integration_test/src/test/resources/log4j.properties
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-409

#411 CCD-2472: Temporarily suppress CVE-2022-0235
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-411

#403 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  test/java/build.gradle
  test/java/config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-403

#412 CVE-2022-0235
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-412
