Repository hmcts/ccd-api-gateway, pull requests merged in 2022-11, with the labels that each got.

#450 CCD-3802 Update to fortify-client version
  test/java/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-450

#437 Ccd 3422 math random hotspot
  app/address/address-lookup.js
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-437

#453 CCD-3916 Update Github actions in workflow -
  .github/workflows/scheduled-dummy-commit.yml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-453
