Repository hmcts/ccd-api-gateway, pull requests merged in 2022-04, with the labels that each got.

#424 suppress cve
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-424

#425 Suppress new vulnerability flag
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-425

#426 --Fixed the Nightly build
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-426

#429 update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-429

#427 CCD-2973: CVE-2022-24785 fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-427
