Repository hmcts/ccd-api-gateway, pull requests merged in 2022-07, with the labels that each got.

#439 CCD-3465 : Suppressions added for CVE-2022-31129
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-439

#440 CCD-3461 : Added suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-440

#423 CCD-2496 Update all repos with multi arch base images
  Dockerfile
  Jenkinsfile_CNP
  acb.tpl.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-423

#442 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-api-gateway-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-442
