Repository hmcts/ccd-api-gateway, pull requests merged in 2022-12, with the labels that each got.

#452 CCD-3942 dependabot minimatch ReDoS vulnerability - resolution minima…
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-452

#458 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped nodejs…
  charts/ccd-api-gateway-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-458

#454 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-454

#461 CCD-4134 CVE-2022-46175 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-461
