Repository hmcts/ccd-api-gateway, pull requests merged in 2023-05, with the labels that each got.

#481 Ccd 1725 fix sonar cloud issues
  app/address/address-lookup.js
  app/oauth2/access-token-request.js
  app/security/cors.js
  test/cache/cache-service.spec.js
  test/user/auth-checker-user-only-filter.spec.js
  test/user/cached-user-resolver.spec.js
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-481

#484 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-484

#482 CCD-4687 Update renovate.json
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-482
