Repository hmcts/ccd-api-gateway, pull requests merged in 2023-02, with the labels that each got.

#472 CCD-4237 CVE-2022-25901 Resolution added cookiejar ^2.1.4, yarn insta…
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-472

#476 CCD-4267
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-476

#474 CCD-4224 Yarn v3 upgrade
  .gitignore
  .travis.yml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Dockerfile
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-474

#475 CCD-4317 Upgrade base charts
  charts/ccd-api-gateway-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-475

#478 CCD-4339: Update package versions
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-478
