Repository hmcts/ccd-api-gateway, pull requests merged in 2023-06, with the labels that each got.

#487 Sample activity service to reduce costs
  app/app-insights/app-insights.js
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-487

#488 Sample remote dependency data as well for activity service
  app/app-insights/app-insights.js
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-488

#490 CCD-4766 : fix for suppressions syntax
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-490
