Repository hmcts/ccd-api-gateway, pull requests merged in 2023-01, with the labels that each got.

#464 CCD-4134 CVE-2022-46175 Redo Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-464

#462 CCD-4134 CVE-2022-46175 json5 v2.2.2 resolution added, yarn install r…
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-462

#456 CCD-4088: updated express to 4.17.3 and removed suppression
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-456

#459 CCD-4097: Auto-suppress CVEs - Node JS apps
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-459

#467 CCD-4173: Auto-suppress CVEs do not allow empty commit
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-467

#463 CCD-3796 Update Node Version - upgraded to 16.15.0
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  acb.tpl.yaml
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-463

#469 CCD-4209 CVE-2017-20165
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-469

#470 CCD-4218 Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-470
