Repository hmcts/ccd-api-gateway, pull requests merged in 2024-04, with the labels that each got.

#526 Updating yarn report with CVE suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-526

#519 Updated version to resolve CVE
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-519

#528 Adding suppression to api-gateway cve
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-528

#527 updated nodejs version from 3.0.0 to 3.1.0 and chart version from 1.2…
  charts/ccd-api-gateway-web/Chart.yaml
  charts/ccd-api-gateway-web/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-527
