Repository hmcts/ccd-api-gateway, pull requests merged in 2024-09, with the labels that each got.

#537 CCD-5861 : CVE-2024-45296 : updated suppressions file
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-537

#539 CCD-5861 : CVE-2024-45296 : updated suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-539

#541 cve_new_
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-541

#544 CVE_reDO
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-api-gateway-web-pr-544
